default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

joint_limits:
  joint1:
    has_velocity_limits: true
    max_velocity: 50.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  joint2:
    has_velocity_limits: true
    max_velocity: 50.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  joint3:
    has_velocity_limits: true
    max_velocity: 50.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  joint4:
    has_velocity_limits: true
    max_velocity: 50.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  joint5:
    has_velocity_limits: true
    max_velocity: 50.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  joint6:
    has_velocity_limits: true
    max_velocity: 50.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  joint7:
    has_velocity_limits: true
    max_velocity: 10.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  joint8:
    has_velocity_limits: true
    max_velocity: 10.0
    has_acceleration_limits: false
    max_acceleration: 0